version: '2'

services:
  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  todomvc-turbolinks:
    depends_on:
      - 'postgres'
    build: .
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/todomvc_production?pool=5
    ports:
      - '${PORT}:3000'

volumes:
  postgres:
