version: '3'

services:
  postgres:
    image: 'postgres:9.6-alpine'
    env_file: .env
    networks:
      - default
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    labels:
      - 'app=todomvc-turbolinks'
      - 'version=${COMPOSE_PROJECT_NAME}'

  todomvc-turbolinks:
    depends_on:
      - 'postgres'
    build: .
    env_file: .env
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 'true'
    ports:
      - '3000'
    networks:
      - default
    labels:
      - 'app=todomvc-turbolinks'
      - 'version=${COMPOSE_PROJECT_NAME}'

volumes:
  postgres:
networks:
  default:
