version: '3'

services:
  postgres:
    image: 'postgres:9.6-alpine'
    env_file: .env
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - default
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  todomvc-turbolinks:
    depends_on:
      - 'postgres'
    build: .
    env_file: .env
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: true
    ports:
      - '${PORT}:3000'
    networks:
      - default

volumes:
  postgres:
networks:
  default:
