version: '2'

services:
  postgres:
    image: 'postgres:9.6-alpine'
    env_file: .env
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  todomvc-turbolinks:
    depends_on:
      - 'postgres'
    build: .
    env_file: .env
    ports:
      - '${PORT}:3000'

volumes:
  postgres:
